services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram_bot_container
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - chroma_db_volume:/app/chroma_db

volumes:
  chroma_db_volume: