version: '3.8' # Phiên bản của Docker Compose

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram_bot_container
    env_file:
      - .env
    restart: unless-stopped